### PR TITLE
Add centos support

### PR DESCRIPTION
**Pull request by johnsmyth**
I added support for Centos, but I also changed the PBIS url to the latest version (8.3) so I bumped the cookbook version to 2.0.0.  The attribute and recipe changes were actually pretty minor, but I made a whole bunch of changes and additions to facilitate more rigorous testing.  As a result, you have to converge the test ad (windows domain controller) first.  I have not had any issues just running 'kitchen verify' and converging and testing them all in order, but it does take about 20 minutes to get through all 5.  I realize that the testing changes are perhaps a bit presumptuous, so I hope you don't mind....

### CODE REVIEW

**Comment by troyready** [comment]
I like it a ton; would love to get this merged.

I'm guessing that you switched off of Matt Wrock's windows image because of missing feature install files? I'd like to find a way to switch back to it (since he keeps it updated well and it seems as good an image as any to standardize on). Could you see about making an optional `source` parameter to the `windows_feature` resources that need it (e.g. `Microsoft-Windows-GroupPolicy-ServerAdmintools-Update`)? I'd be open to either installing it before windows_ad::default or using chef-rewind or whatever.

And once we've got everything else worked out then I'd like to see all of your branches commits squashed down into one (or possibly 2 for the separate features of testing & pbis-version-bump).

**Comment by johnsmyth** [comment]
Unfortunately, some of the windows features that are installed by the default recipe are required in order to install and configure AD with the cookbook (ActiveDirectory-Powershell, for instance).  It seems that the mwrock/Windows2012R2 vagrant box has the source files for these features removed, so it doesn't look like we'll be able to use that box.  Matt Wrock has another published box (mwrock/Windows2012R2Full) that appears to work.  I can switch to that one if you like, however this one doesn't seem to be updated regularly -- he hasn't updated it in 11 months.  Let me know what you think...

**Comment by troyready** [comment]
@kingjared thoughts? I'm inclined to embrace minimal windows images (i.e. requiring the WIM files or whatever to be extracted and hosted for the recipe to access via http), but that may be too extreme.

**Comment by jking916** [comment]
@johnsmyth The box you chose appears to have good community support (even more than Matt Wrock's), so I have no problem using that. In the event that Chef starts maintaining Vagrant boxes for Windows like they do for other platforms (which is a good possibility now that Matt works for Chef) we can re-address this.

**Comment by johnsmyth** [comment]
@troyready - just an FYI, that opentable box is fairly lean (as windows boxes go....).  The packed size is 3.9GB, same as mwrock's:

```
3.9G    /Users/jsmyth/.vagrant.d/boxes/mwrock-VAGRANTSLASH-Windows2012R2
5.2G    /Users/jsmyth/.vagrant.d/boxes/mwrock-VAGRANTSLASH-Windows2012R2Full
2.9G    /Users/jsmyth/.vagrant.d/boxes/opentable-VAGRANTSLASH-win-2008r2-datacenter-amd64-nocm
3.9G    /Users/jsmyth/.vagrant.d/boxes/opentable-VAGRANTSLASH-win-2012r2-standard-amd64-nocm
404M    /Users/jsmyth/.vagrant.d/boxes/opscode-centos-6.5
358M    /Users/jsmyth/.vagrant.d/boxes/opscode-centos-7.1
393M    /Users/jsmyth/.vagrant.d/boxes/opscode-centos-7.2
309M    /Users/jsmyth/.vagrant.d/boxes/opscode-ubuntu-12.04
503M    /Users/jsmyth/.vagrant.d/boxes/opscode-ubuntu-14.04
```

Also, I rebased to a single commit, per your request.

**Comment by jking916** [comment]
@johnsmyth Looks good. I'll run the tests on our end in the next day or two.

**Comment by jking916** [comment]
@johnsmyth Tests look good, thanks for the PR!

**Pull request merged**
